apiVersion: v1
kind: Secret
metadata:
    name: mysecret
    namespace: postgres
type: Opaque
data:
    # base64 postgresdb
    POSTGRES_DB: cG9zdGdyZXNkYg==
    # postgresadmin
    POSTGRES_USER: cG9zdGdyZXNhZG1pbg==
    # admin123
    POSTGRES_PASSWORD: YWRtaW4xMjM=
    # generate base64 echo -n 'admin123' | openssl enc -base64